<?php
/**
 *  @file
 *  Taxonomy View Filter Dropdown
 *  Content/Format change
 */

use \Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;


/**
 *  Implements hook_form_alter()
 */
function cncex_views_form_alter(&$form, $form_state, $form_id) {

  // Filter :: Inventory Taxonomy
  // Create longdash space in child terms in dropdown
  if ($form['#id'] == 'views-exposed-form-filter-all-inventory-default') {
    foreach ($form['term_node_tid_depth']['#options'] as $key => $value) {
      if (is_int($key)) {
        foreach ($value as $row => $data) {
          if ($row == "option") {
          foreach ($data as $drow => $ddata) {
            if (is_int($drow)) {
            if (isset($form['term_node_tid_depth']['#options'][$key]->{$row}[$drow]) &&
                preg_match('/^-/', $form['term_node_tid_depth']['#options'][$key]->{$row}[$drow])) {
                    $word = $form['term_node_tid_depth']['#options'][$key]->{$row}[$drow];
                    $newword = preg_replace('/^-/', ' — ', $word);
                    $form['term_node_tid_depth']['#options'][$key]->{$row}[$drow] = $newword;
                  }
                }
              }
            }
          }
        }
      }
    }

  // Filter :: Manufacturer
  // Populate manufacturers dropdown
  if ($form['#id'] == 'views-exposed-form-filter-manufacturer-default' ||
      $form['#id'] == 'views-exposed-form-filter-all-inventory-default') {

        $query = db_select('node__field_manufacturer', 'm')
          ->fields('m', array('field_manufacturer_value'))
          ->orderBy('field_manufacturer_value', 'ASC')
          ->execute()
          ->fetchAll();

        $options['All'] = '- Manufacturer -';
        foreach ($query as $key => $value) {
          $options[$value->field_manufacturer_value] = $value->field_manufacturer_value;
        }

        $form['field_manufacturer_value'] = [
           '#type' => 'select',
           '#options' => $options,
           '#validated' => TRUE
        ];
    return $form;
  }

}
